version: '3.7'
services:
  database:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
    - '27017:27017'
    volumes:
    - mongodbdata:/data/db
    - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodbdata:
    driver: local